# Generated by Django 5.1.5 on 2025-04-10 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain letters, numbers, spaces, and @/./+/-/_ characters.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
