# Generated by Django 5.1.5 on 2025-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0002_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='requires_attention',
            field=models.BooleanField(default=False),
        ),
    ]
