# Generated by Django 5.1.5 on 2025-04-10 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0004_question_custom_eval_question_eval_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
