# Generated by Django 5.1.5 on 2025-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0005_electronicexam_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicexam',
            name='status',
            field=models.CharField(choices=[('done', 'Complete'), ('progress', 'In Progress'), ('pending', 'Pending'), ('requires_attention', 'Requires Attention')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='electronicexam',
            name='was_done_once',
            field=models.BooleanField(default=False),
        ),
    ]
