# Generated by Django 5.1.5 on 2025-04-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0006_electronicexam_status_electronicexam_was_done_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='manual_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicexam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
