# Generated by Django 5.1.5 on 2025-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0007_studentresponse_manual_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicexam',
            name='can_navigate',
            field=models.BooleanField(default=True, help_text='Allow students to go back and forth between questions'),
        ),
    ]
