# Generated by Django 5.1.5 on 2025-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0008_electronicexam_can_navigate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
