# Generated by Django 5.1.5 on 2025-04-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0009_studentresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='electronic_exam.electronicexam'),
        ),
    ]
