# Generated by Django 5.1.5 on 2025-04-22 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0010_studentresponse_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='electronic_exam.electronicexam'),
        ),
    ]
