# Generated by Django 5.1.5 on 2025-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0011_alter_studentresponse_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicexam',
            name='grades_released',
            field=models.BooleanField(default=False),
        ),
    ]
