# Generated by Django 5.1.5 on 2025-04-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0012_electronicexam_grades_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
