# Generated by Django 5.1.5 on 2025-04-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0013_studentresponse_is_manual_override'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresponse',
            old_name='is_manual_override',
            new_name='is_score_override',
        ),
    ]
