# Generated by Django 5.1.5 on 2025-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaper',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
