# Generated by Django 5.1.5 on 2025-04-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_question_custom_eval_question_eval_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='manual_override',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='rubric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
