# Generated by Django 5.1.5 on 2025-04-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_grade_manual_override_grade_rubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='rubric',
        ),
    ]
