# Generated by Django 5.1.5 on 2025-04-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_remove_grade_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='studentpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.studentpaper'),
        ),
    ]
