# Generated by Django 5.1.5 on 2025-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_grade_studentpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaper',
            name='manual_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='manual_override',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
