# Generated by Django 5.1.5 on 2025-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_studentpaper_manual_name_alter_grade_manual_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('paper', 'Paper Exam'), ('electronic', 'Electronic Exam')], default='paper', max_length=20),
        ),
    ]
