# Generated by Django 5.1.5 on 2025-04-10 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_text', models.TextField()),
                ('manual_score', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('studentpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_issues', to='exams.studentpaper')),
            ],
        ),
    ]
