# Generated by Django 5.1.5 on 2025-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_alter_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaper',
            name='manual_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
