# Generated by Django 5.1.5 on 2025-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_studentpaper_manual_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaper',
            name='manual_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
