# Generated by Django 5.1.5 on 2025-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_studentpaper_manual_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaper',
            name='instructor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
