# Generated by Django 5.1.5 on 2025-04-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_studentpaper_instructor_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpaper',
            name='manual_feedback',
        ),
    ]
