# Generated by Django 5.1.5 on 2025-04-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_studentpaper_manual_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('done', 'Complete'), ('progress', 'Progress'), ('pending', 'Pending'), ('requires_attention', 'Requires Attention'), ('new_papers_after_grading', 'New Papers Need Grading')], default='pending', max_length=30),
        ),
    ]
