# Generated by Django 5.1.5 on 2025-04-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_alter_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='was_done_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('done', 'Complete'), ('progress', 'In Progress'), ('pending', 'Pending'), ('requires_attention', 'Requires Attention'), ('new_papers_uploaded', 'New Papers Uploaded')], default='pending', max_length=30),
        ),
    ]
