# Generated by Django 5.1.5 on 2025-04-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_exam_was_done_once_alter_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exams.exam'),
        ),
    ]
