# Generated by Django 5.1.5 on 2025-04-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_studentpaper_group_key_studentpaper_is_merged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaper',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_papers', to='exams.studentpaper'),
        ),
    ]
