# Generated by Django 5.1.5 on 2025-04-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_studentpaper_merged_into'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_responses', to='exams.grade')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
        ),
    ]
